Dockerfile

The Dockerfile defaults to linux/amd64, this PR sets the GOOS and GOARCH
env values rather than forcing linux/amd64.

Default GOOS and GOARCH to current "go env" value

---

bundle/4.9/manifests/image-references
bundle/art.yaml

Couple errors I caught while trying to test building it through ART.
With those changes applied, we managed to get the following successful builds in brew:
* operator: [special-resource-operator-container-v4.9.0-202107161313.p0.git.d0562b4.assembly.stream](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1665437)
* bundle: [special-resource-operator-bundle-container-v4.9.0.202107161313.p0.git.d0562b4.assembly.stream-1](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1665457)

[ART-3090] Fix manifests for ART builds

---

.patches/getter.patch.go
OWNERS
bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
config/manager/kustomization.yaml
config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
test/e2e/basic/simple-kmod.go
test/e2e/basic/util.go
vendor/helm.sh/helm/v3/pkg/getter/getter.patch.go

This PR syncs the downstream repo with upstream, most importantly to fix the referenced BZ.
The other minor changes from upstream:
- Make sure debug pods in e2e test are assigned to Ready nodes only.
- Add olm skiprange to the "master copy" of the CSV config/manifests/bases/special-resource-operator.clusterserviceversion.yaml so that future bundle updates will keep the change from #32 
- Add pacevedo to reviewers
- Add upstream fix to infoscale special resource.
/cc @SchSeba

Bug 2000226: Unable to have multiple charts in one configmap

---

Makefile.helper.mk
PROJECT
bundle/4.9/bundle.Dockerfile
bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
bundle/4.9/metadata/annotations.yaml
config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml

The SRO CSV name collides with the community operator name.  Because it's easier to rename the one that is not yet publicly available, we can fix this by renaming the downstream CSV (and project) to openshift-special-resource-operator. See BZ and discussion in the ART slack channel for why this is needed.
This will mean that going forward the upstream and downstream bundle will diverge. The upstream bundle can become the community version, and downstream can be the ART version. When we cherry-pick changes from upstream, we will need to regenerate the downstream bundle.
/cc @bthurber @pacevedom @thiagoalessio

Bug 2009888: Rename project to openshift-special-resource-operator 

---

pkg/cluster/cluster.go
pkg/osversion/osversion.go

Fix RHEL version resolution under OCP 4.7.24+, where RHEL version changed from 8.3 to 8.4 and this was mistakenly fixed to 8.3 for all OCP 4.7.z versions.

Bug 2010911: RenderOperatingSystem() returns wrong OS version on OCP 4.7.24

---

bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
bundle/image-references
config/manager/kustomization.yaml

Currently we are unable to run the operator bundle in the openshift/special-resource-operator repository, because it uses a nonexistent image quay.io/openshift/special-resource-rhel8-operator:4.9.   To be consistent with other optional operators we should be using the origin image quay.io/openshift/origin-special-resource-rhel8-operator:4.9.
/cc @pacevedom 
/cc @SchSeba

Bug 2011977: Use origin image in bundle

---

README.md

It make no sense that the d/s README point to the u/s repo.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

Fixing README to point to the d/s repo.

---

pkg/storage/storage.go

This is a backport of https://github.com/openshift-psap/special-resource-operator/pull/197.
/cc @pacevedom

Bug 2033579: Allow the ConfigMap's data field to be empty

---

controllers/runtime.go

Failure to retrieve the pull secret should not return an early error, as it is only found after creating the namespace and this operation has not been done yet.

Bug 2034766: Special Resource Operator(SRO) - no cert-manager pod created in dual stack environment

---

pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/mock_metrics_api.go
pkg/resource/mock_resource_api.go

Define and create a metric that will be later used by the "pre-flight"
upgrade code to trigger alert in case SRO encounters a problem with
driver-container for a specific CR

MGMT-9193: Create metric for upgrade alert

---

config/prometheus/monitor.yaml

Define and deploy PrometheusRule that uses the sro_upgrade_metric
to raise an alert, in case it is needed

MGMT-9231: deployment of PrometheusRule for upgrade alert

---

pkg/resource/resource.go
pkg/resource/resource_test.go

Remove callback annotations from recipes, as it requires custom code in SRO and right now there arent any. This is currently dead code.
Callbacks may be superseded by helm hooks.

Remove callback annotations

---

config/manager/manager.yaml
manifests-k8s/0013_deployment_special-resource-controller-manager.yaml
manifests/0015_deployment_special-resource-controller-manager.yaml
pkg/registry/registry.go
pkg/registry/registry_test.go

Using pull secret in-memory makes running the operator easier in out-of-cluster scenario (using `go run .` against `$KUBECONFIG`)

Use in-memory pull-secret instead of writing to disk

---

pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/mock_cluster_api.go
pkg/registry/mock_registry_api.go
pkg/registry/registry.go
pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go

Instead of fetching and unpacking release image to get the DTK Image URL, a `driver-toolkit` `ImageStream` is used.

Use DTK ImageStream to get an DTK image URL

---

pkg/registry/mock_registry_api.go
pkg/registry/registry.go

This PR adds 2 APIs that:
1) return digest of all the layers in the image, in addition to
repo and repo auth
2) return v1Layer based on a provided repo,digest and auth

MGMT-9551 - extend Regsitry API to allow querring different image layers

---

pkg/upgrade/mock_upgrade_api.go
pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go

This PR adds an API that allows to get an DTK info (full kernel, rt kernel etc')
encoded inside the DTK image

MGMT-9548: adding API to get DTK info based on DTK image

---

pkg/runtime/runtime.go
pkg/runtime/runtime_test.go

1) set platform to OCP (always)
2) remove checking the platfrom of the cluster

MGMT-9686: update package runtime for openshift downstream

---

Makefile

Remove calls to target docker-push, which doesn't exist

Bug 2060007: Makefile fixes for: no rule 'docker-push'

---

pkg/registry/mock_registry_api.go
pkg/registry/registry.go
pkg/runtime/mock_runtime_api.go

PR changes:
1) add ReleaseImageMachineOSConfig API - get the OS data (major/minor etc'), need by preflight
2) change ReleaseManifests API - no need to return version, not in use
3) refactor function, add common helper function getHeaderFromLayer

MGMT-9690: add OS configuration extraction from release image

---

pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/mock_cluster_api.go

This PR include the following changes:
1) new API IsClusterInUpgrade - check if the cluster is currently in the upgrade
2) new API NextUpgradeVersion - returns the OCP image that will be used for upgrade
3) remove validation if various object are present in the cluster, since in OCP cluster
they should be present, and enability to access them should result in clear error

MGMT-9705: add cluster pkg API for preflight support

---

Makefile

Currently manager target in the Makefile produces manager executable, therefore changing the source code files does not trigger rebuilt.
This PR changes the output executable to be sro_manager

MGMT-9766: change Makefile manager target output

---

main.go
pkg/helmer/helmer.go
pkg/helmer/helmer_test.go

Shaves around ~10s from each reconciliation loop.
Helm is used to dry run an install to generate all manifests for later apply in an ordered fashion from SRO. Among the options for the install we have `ClientOnly` set to false. If we look at how helm uses this parameter we find (assuming it is set to false):
- Install config runs using `DryRun`, meaning no actual resources will be created.
- When setting `ClientOnly` to false helm uses an actual kubeclient to talk to the cluster.
- CRDs get installed if not using `DryRun`.
- Capabilities and API versions are retrieved from the cluster.
- Capabilities and API versions are passed to render manifests coalescing values.
- Check if resources already exist in the cluster.
- Dry run active, bail out.
Capabilities are a mixture of API versions …

Use helm libraries as client only

---

Makefile

Since SRO test chart has been moved to use ConfigMap instead of file,
we need to add a target to the Makefile that allows to create load ConfigMsap
containing the chart data (simple-kmod, ping-pong)
into the test cluster of the user (probably, on some beaker machine)
This PR add a target that allows loading such CM into cluster, and provides
infrastructure for expanding to other future recipes

MGMT-9798: Add makefile target for local test ConfigMap deployment

---

pkg/helmer/helmer.go
pkg/helmer/helmer_test.go

For the preflight code we need to preprocess the helm charts of a CR
to get all the resulting yamls, without actually loading them into the cluster.
This PR does the following
1) add an API that just does the helm preprocessing and returns a list of yaml
2) change Run API to use the shared code of the new API

MGMT-9731: add helmer package API for preflight preprocessing

---

controllers/resources.go
controllers/specialresource.go
controllers/specialresource_controller.go
main.go
pkg/helmer/helmer.go
pkg/helmer/helmer_test.go
pkg/resource/mock_resource_api.go
pkg/resource/resource.go
pkg/resource/resource_test.go

The changes in this PR:
1) add API to get a list of Objects from helm YAMLs
2) rename Creator interface to ResourceAPI, and update the code accordingly

MGMT-9763: add resource pkg API to support preflight validations

---

controllers/specialresource_controller.go
pkg/poll/poll.go
pkg/poll/poll_test.go

Remove wait calls from poll package.
Reconciliation loop goes through all yaml files in a helm chart, each of them having the following waiting pattern:
- Wait 5s before doing any checks.
- Check if the resource is available (whatever that is for different resources).
- If it is, return error-free and continue with the next file.
- If not, retry after 5 additional seconds.
- Repeat until 30s mark is reached and return an error.
This means that each file will introduce a significant delay in the loop, preventing other SRs to progress and, in general, taking too long to execute each one.
This PR drops all waiting and replaces them with immediate checks with reconcile errors to allow concurrency. Results of the change are high speedups when reconciling, plus improved responsiveness.

Remove wait from poll package

---

ci/podman.yaml

We will deploy a podman container in the CI ephemeral cluster in order to
build SRO in a disconnected env.
This pod has to mount the pull-secret secret of the cluster, therefore, it
can't be initiated via cli as there is no option to mount a volume
on the pod's creation via cli and k8s doesn't supporting patching volumes
on running pods.

Adding CI artifacts.

---

Makefile

It is currently set to the u/s image on quay.io/openshift-psap org
according to our GH action that does that u/s.
---
The new image is build by OCP Prow on each push https://github.com/openshift/release/blob/a88469e7c9dbe0c5a7443ed54989ee5f59bc9a0a/core-services/image-mirroring/openshift/mapping_origin_4_11#L267

Fixing the default IMG for SRO.

---

OWNERS

Now that the SRO team has fully ramped up on ownership of SRO, I think I can be removed from the OWNERS. I am no longer actively involved in the project and probably shouldn't be selected as a reviewer.
I am always happy to consult on this project when specific issues or questions come up where I can help!

Remove dagrayvid from OWNERS

---

pkg/helmer/helmer.go

Those configmaps are generated upon a special resource creation, and
by setting the owner of those hooks to that special resource we ensure
that the hooks are cleaned up upon the special resource removal.

Adding ownerReference to helm hooks configmaps.

---

pkg/helmer/helmer.go

Debug printouts are dependent on the HELM_DEBUG env variable
which can be set either via enviroment, or via helm enviroment
struct Debug flag configuration.

Removing debug printouts in the cm-getter plugin

---

pkg/lifecycle/lifecycle.go
pkg/utils/logging.go

Enhancing returned errors for pkg/lifecycle.

---

pkg/runtime/runtime.go

Enhancing returned errors for pkg/runtime.

---

pkg/resource/resource.go
pkg/resource/resource_test.go

Enhancing returned errors for pkg/resource.

---

manifests/0014_configmap_special-resource-lifecycle.yaml
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/lifecycle/lifecycle.go
pkg/lifecycle/lifecycle_test.go
pkg/lifecycle/mock_lifecycle_api.go
pkg/poll/poll.go
pkg/poll/poll_test.go

special-resource-lifecycle configmap is used by SRO to monitor the pods of the Daemonsets.
The main use is for DaemonSets with updateStrategy set "onDelete".
With "onDelete" strategy, upon DS update no new pods are created until the old one are deleted externally
(by user or some other code).
In ForDaemonSet function in poll package, we have 3 stages of polling:
1) Check that DS exists
2) in case of onDelete, check DS pods are not present in configmap (meaning they were deleted
3) wait for DS desired number of pods to equal numberAvailble
This PR will remove the configmap, and now will check that all the pods were
deleted by checking that DS generation label and pods generation template label are equal
(meaning that only the new pods are running)

MGMT-10184: Remove special-resource-lifecycle configmap usage

---

pkg/helmer/helmer.go
pkg/helmer/helmer_test.go
pkg/helmer/mock_helmer_api.go
pkg/preflight/preflight.go

This PR makes `pkg/helmer` code use the SpecialResource's name as the Helm release name. This avoids collisions when two SpecialResources are targeting the same chart.

Bug 2070172: Use the SpecialResource's name as Helm release

---

controllers/specialresource.go
internal/controllers/finalizers/specialresource.go
internal/controllers/finalizers/specialresource_test.go

In case of cluster(SRO) upgrade from 4.9 to 4.10 or 4.11,
an SRO CR will contain to finalizers strings, since the finalization
string has changed between 4.9 and 4.10. Current code only removes
current finalization atring, which means that in case of an upgrade
finalization string of 4.9 is left on the CR and it is never deleted
from etcd. This PR will always try to remove also the 4.9 finalization
string together with current finalization string

Bug 2084732: fix SRO CR finalization in case of an upgrade

---

controllers/specialresource.go
controllers/specialresource_controller.go

This PR moves the resulting logging of errors and warning from the
top Reconcile function to the SpecialResourcesReconcile function,
and simplifies the Reconcile function

Bug 2089344: fix the Reconcilition function logs

---

controllers/specialresourcemodule_controller.go

Solves [BZ 2089719](https://bugzilla.redhat.com/show_bug.cgi?id=2089719) by adding the arch when its missing from the release info in DTK (happens in older versions). This renders builds not working when using the `kernelFullVersion` or `rKernelFullVersion` variables in recipes.

Bug 2089719: Add arch to kernel versions

---

bundle/4.11/manifests/openshift-special-resource-operator.v4.11.0.clusterserviceversion.yaml
charts/example/acm-simple-kmod-0.0.1/acm-simple-kmod.yaml
config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
config/samples/sro_v1beta1_specialresource.yaml
docs/debug.md
docs/recipes.md

Manifests from bundle and example in charts still refer to kvc-simple-kmod which leads to errors as[ kvc-simple-kmod repo](https://github.com/openshift-psap/kvc-simple-kmod) is no longer used by SRO in favor of [simple-kmod](https://github.com/openshift-psap/simple-kmod) which does not have [KVC](https://github.com/kmods-via-containers/kmods-via-containers) dependencies.

Bug 2088324: Some manifests still have KVC references

---

charts/example/acm-ice-0.0.1/templates/0001-buildconfig.yaml
charts/example/acm-ice-0.0.1/templates/0002-policy.yaml
charts/example/acm-ice-0.0.1/templates/0003-placement.yaml
controllers/specialresourcemodule_controller.go
pkg/registry/mock_registry_api.go
pkg/registry/registry.go

Add functionality to extract OCP version from images and use it as
a helm variable.
Tweak ICE driver example to fix bug 2093357

Bug 2093357: hub and spokes: add OCP version retrieval and fix ICE driver

---

Makefile
Makefile.helper.mk
pkg/filter/filter.go
test/e2e/basic/available.go
test/e2e/basic/simple-kmod.go
test/e2e/basic/util.go

Because of a backport error, the filtering for managementState field
in the CR was exactly the opposite of what it should be.

Bug 2093444: Fix filtering for management state

---

charts/example/acm-ice-0.0.1/README.md
charts/example/acm-ice-0.0.1/acm-ice.yaml
charts/example/acm-ice-0.0.1/templates/0002-policy.yaml
charts/example/acm-ice-0.0.1/templates/0003-placement.yaml

Since ICE driver must be loaded before kubelet, we need the spokes to
get the image matching the running kernel, and this happens halfway
into the upgrade. Once the node is updated (and upgrade aint finished yet)
the new kernel is running and no updates are made towards ACM in the hub,
meaning the spoke will be waiting for an image that wont ever get built
until managedcluster in the hub is updated.
To fix this, we create a cluster claim looking at the desired image in the
spoke, allowing for fast builds before the upgrade even begins.

Bug 2093357: ACM-ICE: use cluster claims to allow upgrades in spokes 

---

internal/resourcehelper/helper.go

In order to update objects these need to get the resourceVersion from
the existing ones. There is a list to determine which resources should
be able to grab this field and ACM resources were not part of it.

Bug 2093277: Add ACM resources to resourceVersion update list
