Makefile, config/cr/kustomization.yaml, config/cr/specialresource_preamble.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/namespace/kustomization.yaml, config/namespace/namespace.yaml, controllers/conditions.go, controllers/runtime.go, controllers/specialresource.go, controllers/specialresource_controller.go, controllers/status.go, manifests/0000_namespace_openshift-special-resource-operator.yaml, manifests/0002_role_special-resource-leader-election-role.yaml, manifests/0003_role_special-resource-prometheus-k8s.yaml, manifests/0007_rolebinding_special-resource-leader-election-rolebinding.yaml, manifests/0008_rolebinding_special-resource-prometheus-k8s.yaml, manifests/0009_clusterrolebinding_special-resource-manager-rolebinding.yaml, manifests/0011_service_special-resource-controller-manager-metrics-service.yaml, manifests/0012_deployment_special-resource-controller-manager.yaml, manifests/0013_clusteroperator_special-resource-operator.yaml, manifests/0014_servicemonitor_special-resource-controller-manager-metrics-monitor.yaml, manifests/0015_specialresource_special-resource-preamble.yaml
Removed abberviation in namespace and added preamble for SRO to report conditions early
=> Removed abberviation in namespace and added preamble for SRO to report conditions early

Dockerfile
Inclusion in the CVO requires architecture team agreement.
=> Disabling as CVO operator

OWNERS, bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/samples/sro_v1beta1_specialresource.yaml
This PR will fix [BZ 1986713](https://bugzilla.redhat.com/show_bug.cgi?id=1986713) with the following change:
* Update config/samples/sro_v1beta1_specialresource.yaml in order to update aml-examples field in bundle
=> Bug 1986713: Update alm-examples to working version of simple-kmod

OWNERS, bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/2000-infoscale-rest-certificate.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/4000-infoscale-fencing-certificate.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/4100-infoscale-fencing-driver.yaml, config/rbac/role.yaml, manifests/0004_clusterrole_special-resource-manager-role.yaml, manifests/0014_deployment_special-resource-controller-manager.yaml, pkg/poll/poll.go, pkg/rbac/rbac.go, test/e2e/basic/available.go
https://github.com/openshift-psap/special-resource-operator/pull/100
https://github.com/openshift-psap/special-resource-operator/pull/99
https://github.com/openshift-psap/special-resource-operator/pull/98
https://github.com/openshift-psap/special-resource-operator/pull/95
=> Bug 2009424: poll.go Deployment availability bug fix and Veritas SpecialResource fixes

OWNERS, bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/2000-infoscale-rest-certificate.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/4000-infoscale-fencing-certificate.yaml, charts/infoscale/infoscale-vtas-0.0.1/templates/4100-infoscale-fencing-driver.yaml, config/rbac/role.yaml, manifests/0004_clusterrole_special-resource-manager-role.yaml, manifests/0014_deployment_special-resource-controller-manager.yaml, pkg/poll/poll.go, pkg/rbac/rbac.go, test/e2e/basic/available.go
…ialResource fixes (#38)
* Add preamble creation to e2e test (#95)
Signed-off-by: Pablo Acevedo Montserrat <pacevedo@redhat.com>
* Fix ReplicaSet upgrade checks (#98)
Signed-off-by: Pablo Acevedo Montserrat <pacevedo@redhat.com>
* Add bthurber, ybettan, yevgeny-shnaidman to OWNERS (#100)
Signed-off-by: David Gray <dagray@redhat.com>
* Infoscale fencing afterhook and other enhancements (#99)
* Adding fencing afterhook podtemplate
Rbac changes for fencing afterhook
* Added secret to support DNS resource
* Update bundle and manifests
Co-authored-by: Trishnendu <trishnendu.ghorai@veritas.com>
Co-authored-by: David Gray <dagray@redhat.com>
Co-authored-by: David Gray <40244437+dagrayvid@users.noreply.github.com>
Co-authored-by: Veritas Technologies LLC <opensource@veritas.com>
Co-authored-by: …
=> [release-4.9] Bug 2009530: poll.go Deployment availability bug fix and Veritas SpecialResource fixes

bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml, config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Also remove Networking and add OpenShift Optional categories
=> Bug 2010931: Remove "Drivers and plugins" category from CSV

bundle/art.yaml, bundle/openshift-special-resource-operator.package.yaml, bundle/special-resource-operator.package.yaml
Change bundle/art.yaml to use the new CSV
Signed-off-by: Pablo Acevedo Montserrat <pacevedo@redhat.com>
=> Bug 2009888: SRO package name collision between official and community version

pkg/upgrade/upgrade.go, pkg/upgrade/upgrade_test.go, vendor/github.com/onsi/ginkgo/extensions/table/table.go, vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
Upstream PR [#149](https://github.com/openshift-psap/special-resource-operator/pull/149)
=> Bug 2024586: Special Resource Operator(SRO) - Empty image in BuildConfig when using RT kernel

api/v1beta1/specialresource_types.go, config/crd/bases/sro.openshift.io_specialresources.yaml, manifests-k8s/0001_customresourcedefinition_specialresources.sro.openshift.io.yaml, manifests/0001_customresourcedefinition_specialresources.sro.openshift.io.yaml, pkg/helmer/api/v1beta1/helmer_types.go
Mark unused types as such.
Re-generate manifests.
Picked from upstream PR https://github.com/openshift-psap/special-resource-operator/pull/232.
=> Bug 2031875: Improve documentation for the SpecialResource API

pkg/poll/poll.go
When there is more than one `buildconfig` resource in the same namespace, poll package queries and waits for all builds, ignoring the build owner, and in turn, possibly waiting on not owned resources. Also fixes waiting for not yet created build pods.
=> Fix poll pkg bug for buildconfig resources

api/v1beta1/specialresource_types.go, config/crd/bases/sro.openshift.io_specialresources.yaml, controllers/specialresource.go, pkg/filter/filter.go, pkg/filter/filter_test.go
* Support for operator Force/Managed/Removed/Unmanaged states
Add managementState e2e tests
* Filter out unmanaged states for reconciling
Co-authored-by: Pablo Acevedo Montserrat <pablo.acevedo.m@gmail.com>
=> Support for operator Force/Managed/Removed/Unmanaged states

pkg/upgrade/upgrade.go, pkg/upgrade/upgrade_test.go
Every reconciliation loop starts by grabbing the DTK image, extracting last layer and then look up some metadata in it. Since we are reading from containers in the registry this information is not going to change for the same image, therefore its not needed to check everytime as we know the outcome.
This PR stores the information upon first retrieval and later on shaves 5s off each reconcile loop.
=> Cache DTK last layer info

controllers/resources.go, controllers/scale_up_down.go, controllers/specialresource.go, internal/controllers/finalizers/specialresource.go, main.go, pkg/assets/assets.go, pkg/clients/clients.go, pkg/filter/filter.go, pkg/helmer/helmer.go, pkg/registry/registry.go, pkg/resource/resource.go, pkg/runtime/runtime.go, pkg/upgrade/upgrade.go
Reduce amount of logging in case of happy path.
=> Rework logs in all packages

README.md
---
Referring to https://github.com/openshift/special-resource-operator/issues/102
=> Sharpen the dependency on NFD in README.md.

CONTRIBUTING.md
This is important to allow us to easily understand why changes where
made without the need of figuring out the code.
=> Adding a doc section on how to write good commit messages.

Makefile
'make unit-test' to run the whole suit.
'make unit-test TEST=pkg/pkg_name' to run a specific pkg.
=> Allowing running a specific pkg/spec unit-test.

pkg/kernel/kernel.go
This is part of the logging enhancement effort which says that all
errors should be wrapped with its context and logging should only be
done at the reconciliation loop level.
=> Enhancing returned errors for pkg/kernel.

controllers/specialresourcemodule_controller.go
Force a deterministic order when running builds for SpecialResourceModule. The nature of distributed kernel modules in hub & spokes prevent running build pods in parallel without complex management in the operator.
On top of that, the number of different versions to build at a time aint high, so parallel builds wont render a tangible benefit.
=> Bug 2079869: Builds for multiple kernel versions should be ran in parallel when possible

controllers/specialresourcemodule_controller.go
=> Enhancing returned errors for specialresourcemodule controller.

controllers/specialresource.go, controllers/specialresource_controller.go
=> Enhancing returned errors for specialresource controller.

api/v1beta1/specialresource_types.go, config/crd/bases/sro.openshift.io_specialresources.yaml, controllers/specialresource.go, pkg/filter/filter.go
Support for operator Force/Managed/Removed/Unmanaged states
=> Bug 2083486: Support for operator Force/Managed/Removed/Unmanaged states

bundle/art.yaml, bundle/openshift-special-resource-operator.package.yaml
=> Bug 2081821: Fixing a typo in the bundle string substitution for ART.

bundle/4.11/manifests/openshift-special-resource-operator.v4.11.0.clusterserviceversion.yaml, bundle/4.11/manifests/sro.openshift.io_preflightvalidations.yaml, bundle/4.11/manifests/sro.openshift.io_specialresourcemodules.yaml, bundle/4.11/manifests/sro.openshift.io_specialresources.yaml, config/samples/sro_v1beta1_specialresource.yaml, manifests/0001_customresourcedefinition_preflightvalidations.sro.openshift.io.yaml, manifests/0003_customresourcedefinition_specialresources.sro.openshift.io.yaml
Include latest CRD changes and update CSV.
=> Bug 2081821: Update bundle for 4.11

charts/example/acm-simple-kmod-0.0.1/templates/0002-policy.yaml
Adds the namespace creation to the policy for the spokes.
=> Bug 2092572: Add namespace creation to acm-simple-kmod

charts/example/acm-ice-0.0.1/acm-ice.yaml, charts/example/acm-simple-kmod-0.0.1/acm-simple-kmod.yaml
Remove team members users referenced in registry config
from ACM SRM examples.
=> Bug 2096162: Use official registries for ACM examples

controllers/finalizers.go
1) In case of cluster(SRO) upgrade from 4.9 to 4.10 or 4.11,
an SRO CR will contain to finalizers strings, since the finalization
string has changed between 4.9 and 4.10. Current code only removes
current finalization atring, which means that in case of an upgrade
finalization string of 4.9 is left on the CR and it is never deleted
from etcd. This PR will always try to remove also the 4.9 finalization
string together with current finalization string
2) in case of cache miss in node labels , error should be returned
so that new reconcilation looped will be initialized, the cache updated
and label removed on the next loop run
=> Bug 2086432: fix SRO CR finalization in case of an upgrade

README.md
=> Fixing the parameter order in scripts/make-cm-recipe.
